services:
  outline:
    image: docker.getoutline.com/outlinewiki/outline:latest
    container_name: outline
    env_file: ./.env
    ports:
      - 3000:3000
    volumes:
      - ./dockers/outline:/var/lib/outline/data
    depends_on:
      - postgres
      - redis
    networks:
      - workspace

  redis:
    image: redis
    container_name: outline-redis
    env_file: ./.env
    ports:
      - 6379:6379
    volumes:
      - ./dockers/redis.conf:/redis.conf
    command: ['redis-server', '/redis.conf']
    healthcheck:
      test: ['CMD', 'redis-cli', 'ping']
      interval: 10s
      timeout: 30s
      retries: 3
    networks:
      - workspace

  postgres:
    image: postgres:latest
    container_name: outline-postgres
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      DATABASE_SSL: ${DATABASE_SSL}
    ports:
      - 5432:5432
    volumes:
      - ./dockers/postgresql:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER}"]
      interval: 30s
      timeout: 20s
      retries: 3
    networks:
      - workspace

volumes:
  dockers:

networks:
  workspace:
